openapi: 3.0.3
info:
  title: User Management API
  version: 1.0.0
  description: OpenAPI for Auth (signin, refresh) and user management
servers:
  - url: http://localhost:8080
    description: Local development server